Repository GetStream/stream-chat-js, pull requests merged in 2020-11, with the labels that each got.

#488 fix #487: form data file name in browser
  src/utils.ts
  test/integration/test.js
Labels: bug

#505 optional parent_id in stopTyping
  src/channel.ts
Labels: enhancement

#504 Add channel export API
  src/client.ts
  src/types.ts
  test/integration/channel_export.js
  test/integration/gdpr.js
Labels: enhancement

#498 Fix/unread count mutes
  src/channel.ts
  src/client.ts
  test/unit/channel.js
  test/unit/channel_state.js
  test/unit/client.js
  test/unit/utils.js
Labels: bug, enhancement

#509 fix: duplicated new messages by current user
  src/channel.ts
Labels: bug
